version: '3'
services:
  runner:
    restart: unless-stopped
    image: myoung34/github-runner:latest
    expose:
      - '8080'
    environment:
      - REPO_URL=https://github.com/pssgoifo/pokedex-go
      - RUNNER_TOKEN=AQYUZXPLYTIGC36P674QDJ3ACQM2Q
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

    logging:
      driver: 'json-file'
      options:
        max-size: '100m'
        max-file: '5'

